version: 2.1
jobs:
  build_image:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker
      - run: 
           name: build docker image
           command:
              docker build --tag=rab7a:${CIRCLE_BUILD_NUM} .
              docer images
      - run:
           name: push2dockerhub
           command: |
             dockerpath="Amira-web-creator/rab7a:${CIRCLE_BUILD_NUM}"
             docker tag rab7a:${CIRCLE_BUILD_NUM} $dockerpath
             echo "Docker ID and IMG:$dockerpath"
             echo "$DOCKER_PASS" | docker login --username $MY_DOCKER_VAR --password-stdin
             docker image push $dockerpath
   

workflows:
  docker:
    jobs:
      - build_image
